### ISSUE TITLE
Modify index.js to handle wrapped LAS files, meaning lines longer than 80 characters get continued on next line. 

### ISSUE THREAD

**Issue by JustinGOSSES** [JustinGOSSES/wellio.js#12]
Modify index.js to handle wrapped LAS files, meaning lines longer than 80 characters get continued on next line. Current wellio.js fails with LAS files that are wrapped. 

https://github.com/JustinGOSSES/wellio.js/blob/master/dist/index.js

This was first suggested by  @oze4  in issue #5.

This would be a good first issue and after a quick look seems like it would involve editing lines 158-194 in index.js. 

Please refer to http://www.cwls.org/las/

**Comment by dcslagel** [comment]
There is a test for this feature.  It is currently disabled with '.skip'.

To run the test:    
1. Edit test_blank_line_in_header.js to remove '.skip'
2. tape dist/test/las2json/test_blank_line_in_header.js

Note the test currently only tests that the las source file (with wrapped data) will be read without throwing an error.  Once that is passed successfully additional test may need to be added to validate the data was parsed properly.

**Comment by JustinGOSSES** [comment]
Should we unwrap the files by default as an initial preprocessing step?

Would that create any problems?

**Comment by dcslagel** [comment]
@JustinGOSSES,

I am just now seeing your comment to look at unwrapping as a preprocessing step.  I had been working on an alternative solution which is in pull request #31.  See if it is also a satisfactory solution or if it need changes.

Thanks,
DC

**Comment by dcslagel** [comment]
@JustinGOSSES 

With pull request #31 merged, do we want to keep this ticket open for additional work in this area or can it be closed now?

Thanks,

DC

**Comment by JustinGOSSES** [comment]
I'll change this to "won't fix". I think a pre-processing step is a safer approach but not really needed right now... want to keep it for now but not worked on.

**Comment by dcslagel** [comment]
@JustinGOSSES,

I'm wondering if we could handle this differently.  Below is a proposal. See if it looks like a good way to go. If not, that's okay, but I thought I would run it by you anyways.

- Move 'Unwrap the files by default as an initial preprocessing step' to a separate ticket.
- Close this ticket.

The thinking for this proposal is that the integration of #31 did enable processing LAS files with wrapped lines which is this issue.

Thanks,

DC
