### ISSUE TITLE
Create notebook or file that documents which tests fail & why &  propose fixes to wellio code to fix.

### ISSUE THREAD

**Issue by JustinGOSSES** [JustinGOSSES/wellio.js#16]
Create notebook or file that documents which tests fail & why &  propose fixes to wellio code to fix.

- Not sure best way to package this...but probably good to make a place for examples of tests that fail and reasons why first... then propose changes to wellio.js parsing code to handle. I suspect at least some of the tests fail for related reasons. This might bring them to surface.

Tagging @dcslagel as you're working in this direction. I'll be unable to spend time on this until next week.

**Comment by dcslagel** [comment]
Would making a github issue for each of the current tests that are failing/skipped?  The benefit of this approach are that each test issue is visible in the main GitHub display.

**Comment by JustinGOSSES** [comment]
Each has its benefits I suppose. Let's go with github issues as you propose though.

**Comment by JustinGOSSES** [comment]
Relatedly - I altered the github actions script in https://github.com/JustinGOSSES/wellio.js/tree/master/.github/workflows such that it seems to work now. 

It uses the las2json and test-all scripts defined in package.json as currently set up. 

Theoretically, it should give us a test fail message when a pull request is submitted that fails tests though I haven't tested that well yet.

**Comment by dcslagel** [comment]
@JustinGOSSES,

Per this conversation, I created issues 20 - 24 to track progress on the current test failures.  

DC
