### ISSUE TITLE
double check that recent updates to npm for v 0.1.6 didn't break any observable notebooks or demos

### ISSUE THREAD

**Issue by JustinGOSSES** [JustinGOSSES/wellio.js#35]
double check that recent updates to npm for v 0.1.6 didn't break any observable notebooks or demos

**Comment by dcslagel** [comment]
Are there tests that validate the notebooks and demos?

DC

**Comment by JustinGOSSES** [comment]
Aside from using them, no. They're kinda integration tests.

I just went through them all. Everything still works.

**Comment by JustinGOSSES** [comment]
https://observablehq.com/search?query=wellio the Observable query does a good job at getting all the notebooks that use wellio.js
