### ISSUE TITLE
BUG: fs for file uploading works with node.js but not in jupyter notebook

### ISSUE THREAD

**Issue by JustinGOSSES** [JustinGOSSES/wellio.js#40]
BUG: fs for file uploading works with node.js but not in jupyter notebook

Probably need to have the file upload function figure out which type of environment it is in and then use the appropriate file upload method. This has likely been figured out before, so might pull in a library for it or use an example?

This was mentioned in issue #7 
https://github.com/JustinGOSSES/wellio.js/issues/7#issuecomment-586723761

and relates to issue #39

**Comment by JustinGOSSES** [comment]
Apparently this can also cause a problem when wellio.js is used by wellioviz on certain browsers. Really need to find an alternative to fs that is more flexible to different OSs.

**Comment by dcslagel** [comment]
@JustinGOSSES,

I'm interested to work on this.  Is there a test that can be run to reproduce the current fs failure in a Jupyter notebook or Angular bundle?  Or optionally, the steps to reproduce the failure?

Thanks,

DC

**Comment by dcslagel** [comment]
I'm working with "wellio.js/notebooks/wellio.js and lasio test.ipynb" on a local jupyter server.

Currently at "wellio.read_json('data.json')" there is a Thrown message of { Error: ENOENT: no such file or directory, open 'data.json'\n"..}".   That looks to be a path problem, so checking that first but expecting to find a 'fs()' issue after I know the code is finding the data.json file.

DC

**Comment by dcslagel** [comment]
See current potential solution and discussion of related issue at #47.

DC

**Comment by JustinGOSSES** [comment]
just getting back to this..sorry for delay. 

%%node in a python notebook has always been somewhat flaky for me. Part of the reason is error are frequently JavaScript when I expect them to be python. Hence, I forget to look in inspector and expect them to be output below the cell.

I've seen something similar to 'data.json'\n"..}". when there is a newline from javascript copy and paste that is invisible but there...hence the \n that suddenly appears in your error.

**Comment by dcslagel** [comment]
@JustinGOSSES,

Just checking with #48 merging what needs to be worked out to resolve this issue?

Thanks,
DC

**Comment by JustinGOSSES** [comment]
Good reminder. 

I'm not sure. I'll want to check it in both Jupyter & when wellioviz gets used in angular as problems were seen in both cases. I'll try to tackle this sometime this week.

**Comment by dcslagel** [comment]
Okay, That sounds good.

Thanks!,
DC
