### ISSUE TITLE
Redo some of the las -> json parsing to more closely match the 2.0 specification. 

### ISSUE THREAD

**Issue by JustinGOSSES** [JustinGOSSES/wellio.js#5]
Redo some of the las -> json parsing to more closely match the 2.0 specification. 

Currently, the code works but some weird edge cases might cause problems. 

Particularly, using the first space after the unit string as deliminator instead of number of characters and then triming the spaces out. 

http://www.cwls.org/wp-content/uploads/2017/02/Las2_Update_Feb2017.pdf

**Comment by JustinGOSSES** [comment]
Having a test suite that leverages wells known to be valid but problematic might be a good way to handle this in addition to close reading of LAS standard.

**Comment by kinverarity1** [comment]
It'd be great to have a common suite of LAS files to test against, particularly grouped by:

- Conformant to spec but designed to test edge cases
- Non-conformant to spec but in a way that a library should be expected to parse
- Non-conformant and unreasonably challenging for a library to parse

The current lasio test suite is a mix of all these.

**Comment by oze4** [comment]
Are there plans to add wrapped .las support? I noticed wrapped .las files do not work..

**Comment by JustinGOSSES** [comment]
Yes, that's a good suggestion @oze4 . It could be added. Breaking it off into its own separate issue here #12
