### ISSUE TITLE
wellio <-> lasio (python)

### ISSUE THREAD

**Issue by JustinGOSSES** [JustinGOSSES/wellio.js#7]
Would be nice to be able to convert back and forth between a LASIO.py object and a wellio.js JSON object. They are both objects, so this is probably just a matter of mapping? I'm assuming both retain all the information in the original LAS file.

**Comment by kinverarity1** [comment]
One of my to-dos (kinverarity1/lasio#107) is to implement a lasio.LASFile.json property attribute, with the ability to accept json and recreate lasio.LASFile object. 

If we make sure the JSON format that lasio uses stays the same as whatever wellio.js is using, should be straightforward to achieve this?

(BTW nice work!)

**Comment by JustinGOSSES** [comment]
Thanks! Easy conversion back and forth between the two would be great. I'm not familiar with LASIO's JSON process but I'm reading up on it here: https://lasio.readthedocs.io/en/latest/_modules/lasio/las_items.html?highlight=json .

**Comment by JustinGOSSES** [comment]
My general idea for a JSON format (could still change) was to have everything be objects {} of objects {} with the values of each object either being another object or a single string. The one exception is the "CURVES" block, which is a single "CURVES" object with keys of individual curves names and a key of an array [] that holds that curves data.  The advantage of this format is it is valid JSON and calling everything becomes very literal if you know what is in the well. If you don't know what is in the well, you can just call for a list of the keys for that information block. For example, you can call for the keys in the "CURVES" block and get a list of all the curve names.

**Comment by JustinGOSSES** [comment]
One piece of information I wasn't sure the best way to handle was the "GENERATED" part of the "WELL INFORMATION" block. It has different information than the rest of the "WELL INFORMATION" block. This is potentially an issue because in the rest of the blocks all objects in a block follow the similar syntax. Because things are similar, you can write one function to handle any object in that block. The "GENERATED" line kinda throws that off as the value is a string "" not another "MNEM" object as is the case with all the lines below it. This is easy to see in the readme.

 I considered having it be its own block within the JSON, perhaps a "WELL INFORMATION - GENERATED" block even though it isn't in a LAS file.  ----- Any thoughts or preferences anyone?

**Comment by kinverarity1** [comment]
Sounds like a good plan. If I understand correctly would this line from your readme example

```
BHTD.M        733.8                : BHTDEP       - MAXIMUM RECORDED TEMPERATURE
```

become

```json
{
    "PARAMETER INFORMATION": {
        "mnemonic": {
            "BHTD"
        },
        "unit": {
            "M"
        },
        "value": {
            "733.8"
        },
        "description": {
            "BHTDEP       - MAXIMUM RECORDED TEMPERATURE"
        }
    }
}
```

? Not sure if I got it right.

Some other things

(1) When you say generated, I assume you mean the comments? e.g.

```
# Generated from Intellog Unique Number	CW_73_75/WELL/2722
```

At the moment lasio discards these lines, but I shouldn't. We could add them to a new section, like you suggest, maybe "COMMENTS"?

(2) Consistent names for section titles. My [current approach]((https://lasio.readthedocs.io/en/latest/header-section.html#tutorial) is to use ``Version``, ``Well``, ``Parameter`` etc. , but I'd be happy to change it. 

(3) Deal with free-text sections like ~OTHER and potentially non-standard ones, e.g. [this test](https://github.com/kinverarity1/lasio/blob/master/tests/test_enhancements.py#L80) reads [this LAS example](https://github.com/kinverarity1/lasio/blob/master/tests/examples/non-standard-header-sections.las)

**Comment by dcslagel** [comment]
@JustinGOSSES @kinverarity1 

I made a very rough branch #32  to explore and identify potential implementation details for this issue.  When you have a chance could you take a look?

Thank you,
DC

**Comment by dcslagel** [comment]
@JustinGOSSES @kinverarity1,

Pull request #33 is an implementation of reading the current Lasio json output. It is based on the discussion and exploratory work done on #3 

DC

**Comment by JustinGOSSES** [comment]
I tried the read_json() function to read in LASIO style JSONs in a Jupyter notebook that was using %% node magics to run both JS & Python in the same notebook. I ran into a problem where the fs node.js library wasn't working correctly. I'm not sure why but it might have something to do with it being run as a magic? 

Here is my notebook: https://github.com/JustinGOSSES/wellio.js/blob/master/notebooks/wellio.js%20and%20lasio%20test.ipynb

I got the lasio -> wellio transfer to work, however, I had to skip the fs step that loads the file. Instead I brought in a python dict of the lasio JSON and started with that and used the rest of the read_json() function. That then worked as you see in the notebook. 

 **My suggestion is to break the read_json function into two functions. One read a file in and the other converts the dict style.** 

That way people can skip the writing/reading of files step if they want to. Also it helps getting around problems like I had.

**Comment by dcslagel** [comment]
This is good info!  Yes, splitting read_json into two functions is a good suggestion, one for getting a file and one for parsing the file.  

 I think fs doesn't work in web environments because browser JavaScript shouldn't have access to the host's file system.  So the get_file function probably needs to check which environment it is in then get the file in the environment appropriate manner.  

I am not yet familiar if the Jupyter notebook has additional considerations so that needs to be looked at..

**Comment by JustinGOSSES** [comment]
Added 2 issues to address this #39 for splitting read_json() function into two parts and #40 for having a function that figures out which method of loading files to use based on the environment

**Comment by JustinGOSSES** [comment]
Just FYI - it seems the read_json function doesn't work quite right yet. It makes a JSON but that JSON isn't a valid wellio JSON. Found this out when trying to use it with wellioviz. No time to right up in depth review but work is ongoing here: https://github.com/JustinGOSSES/wellio.js/blob/master/notebooks/wellio.js%20and%20lasio%20test.ipynb
