### ISSUE TITLE
Fails when using file containing an ~OTHER section

### ISSUE THREAD

**Issue by kinverarity1** [JustinGOSSES/wellio.js#9]
Currently fails to load a LAS file with an ~O section e.g. https://raw.githubusercontent.com/kinverarity1/lasio/master/tests/examples/2.0/sample_2.0.las

**Comment by JustinGOSSES** [comment]
Fixed the las2json() function in wellio.js file such that the ~O section is caught now and the test las file given above works. 

However, I haven't run many test wells through wellio.js or created a test suite, which should be part of making the parsing more robot as noted in issue #5.(https://github.com/JustinGOSSES/wellio.js/issues/5)
